M.core_completion={};M.core_completion.init=function(Y){var changeDetector=Y.one('#completion_dynamic_change');if(changeDetector.get('value')>0){changeDetector.set('value',0);window.location.reload();return;}
var handle_success=function(id,o,args){Y.one('#completion_dynamic_change').set('value',1);responseJson=JSON.parse(o.responseText);if(responseJson.status!='OK'){alert('An error occurred when attempting to save your tick mark.\n\n('+o.responseText+'.)');}else{var current=args.state.get('value');if(current==1){$(args.form).attr('data-completionstate',0)
args.state.set('value',0);args.image.set('src',M.util.image_url('i/completion-manual-y','moodle'));args.image.set('alt',M.str.completion['completion-alt-manual-y']);args.image.set('title',M.str.completion['completion-title-manual-y']);analytics.track('User Marked Complete',{'action_id':'lms.coursework.marked_complete.success','course':window.i11l.LMSContext.course.name?window.i11l.LMSContext.course.name:null,'course_uuid':window.i11l.LMSContext.course.uuid?window.i11l.LMSContext.course.uuid:null,'section_id':window.i11l.LMSContext.course.section_id?window.i11l.LMSContext.course.section_id:null,'section_uuid':window.i11l.LMSContext.course.section_uuid?window.i11l.LMSContext.course.section_uuid:null,'courseRole':window.i11l.LMSContext.course.role,'course_module_id':responseJson.cm.id,'module_name':responseJson.cm.name,'module_type':responseJson.cm.modname,'site':window.i11l.LMSContext.site.id});}else{$(args.form).attr('data-completionstate',1)
args.state.set('value',1);args.image.set('src',M.util.image_url('i/completion-manual-n','moodle'));args.image.set('alt',M.str.completion['completion-alt-manual-n']);args.image.set('title',M.str.completion['completion-title-manual-n']);}}
updateClock(current,Y,args);};var handle_failure=function(id,o,args){alert('An error occurred when attempting to save your tick mark.\n\n('+o.responseText+'.)');};var toggle=function(e){e.preventDefault();var form=e.target;var cmid=0;var completionstate=0;var state=null;var image=null;var inputs=Y.Node.getDOMNode(form).getElementsByTagName('input');for(var i=0;i<inputs.length;i++){switch(inputs[i].name){case'id':cmid=inputs[i].value;break;case'completionstate':completionstate=inputs[i].value;state=Y.one(inputs[i]);break;}
if(inputs[i].type=='image'){image=Y.one(inputs[i]);}}
var cfg={method:"POST",data:'id='+cmid+'&completionstate='+completionstate+'&fromajax=1&sesskey='+M.cfg.sesskey,on:{success:handle_success,failure:handle_failure},arguments:{state:state,image:image,form:form}};Y.use('io',function(Y){Y.io(M.cfg.wwwroot+'/course/togglecompletion.php',cfg);});};var updateClock=function(iState,Y,args){var inputs=Y.Node.getDOMNode(args.form).getElementsByTagName('input');for(var i=0;i<inputs.length;i++){switch(inputs[i].name){case'section_id':var iSectionId=inputs[i].value;break;}}
var formSection=document.getElementById('form-'+iSectionId);if(formSection)
{var iTotal=formSection.total_mods.value;var iChecked=formSection.marked_mods.value;if(iState==1){iChecked=parseInt(iChecked)+1;}
else{iChecked=parseInt(iChecked)-1;}
formSection.marked_mods.value=iChecked;var iPercentage=((iChecked/iTotal)*100);iPercentage=Math.round(iPercentage);if($('#form-'+iSectionId).closest('.content').find('[progress-pie]').length){updateProgressPie($('#form-'+iSectionId).closest('.content').find('[progress-pie]'),iPercentage);$('#form-'+iSectionId).closest('.content').find('.progress-ratio').text(iChecked+' / '+iTotal)}
if(iPercentage>0){sText=iPercentage+" % Complete";}
var imageName='';if(iPercentage==0){sText="Not Started";imageName="not-started";}
else if(iPercentage==100){sText="Completed";imageName="completed";}
else if(iPercentage>0&&iPercentage<=35){imageName="25percent";}
else if(iPercentage>35&&iPercentage<=60){imageName="50percent";}
else if(iPercentage>60&&iPercentage<=99){imageName="75percent";}
var divComplete=document.getElementById('completion_result_'+iSectionId);divComplete.innerHTML='<img src="'+M.util.image_url(imageName,'theme')+'"> '+sText;}};Y.all('form.togglecompletion').each(function(form){if(!form.hasClass('preventjs')){Y.on('submit',toggle,form);}});var help=Y.one('#completionprogressid');if(help&&!(Y.one('form.togglecompletion')||Y.one('.autocompletion'))){help.setStyle('display','none');}};var updateProgressPie=function(progress_pie,percent){var size=progress_pie.attr('diameter');var svgns="http://www.w3.org/2000/svg";var chart=document.createElementNS(svgns,"svg:svg");chart.setAttribute("width",size);chart.setAttribute("height",size);chart.setAttribute("viewBox","0 0 "+size+" "+size);var back=document.createElementNS(svgns,"circle");back.setAttributeNS(null,"cx",size/2);back.setAttributeNS(null,"cy",size/2);back.setAttributeNS(null,"r",size/2-1);back.setAttributeNS(null,"fill","transparent");back.setAttributeNS(null,"stroke-width","2px");chart.appendChild(back);var path=document.createElementNS(svgns,"path");var unit=(Math.PI*2)/100;var startangle=0;var endangle=percent*unit-0.001;var x1=(size/2)+(size/2)*Math.sin(startangle);var y1=(size/2)-(size/2)*Math.cos(startangle);var x2=(size/2)+(size/2)*Math.sin(endangle);var y2=(size/2)-(size/2)*Math.cos(endangle);var big=0;if(endangle-startangle>Math.PI){big=1;}
var d="M "+(size/2)+","+(size/2)+" L "+x1+","+y1+" A "+(size/2)+","+(size/2)+" 0 "+big+" 1 "+
x2+","+y2+" Z";path.setAttribute("d",d);chart.appendChild(path);progress_pie.html(chart);}