function send_contact_request(userid,contactid,contactname,pagenum,current_userid,personal_message){Ext.Ajax.request({url:M.cfg.wwwroot+'/local/utilities/contacts/action.php',method:'GET',success:function(response){if(response['responseText'].indexOf('success')>=0){Ext.Msg.alert('Success','Your request has been sent to '+contactname+' successfully!');reload_contact(pagenum,current_userid);}
else{Ext.Msg.alert('Error','Your request with '+contactname+' was unsuccessful.');}},failure:function(){Ext.Msg.alert('Error','An error occurred on your request with '+contactname+'.  Please try again. If problems persist, please contact us.')},params:{userid:userid,contactid:contactid,action:'add',msg:personal_message}});}
function contact_add_req(userid,contactid,contactname,pagenum,current_userid){if($('[ng-app="onlineCampusApp"]').length>0){send_contact_request(userid,contactid,contactname,pagenum,current_userid,'');}else{Ext.MessageBox.show({title:'Add '+contactname+' as contact',msg:'Add a personal message: (optional)',width:300,buttons:Ext.MessageBox.OKCANCEL,multiline:true,fn:function(btn,text){if(btn=='ok'){send_contact_request(userid,contactid,contactname,pagenum,current_userid,text);}}});Ext.MessageBox.getDialog().getEl().setStyle('z-index','8000000');}};function removeContactNotification(elem){mainNode=elem.parentNode.parentNode.parentNode.parentNode.parentNode;if(Object.prototype.toString.call(mainNode)=='[object HTMLLIElement]')
{mainNode.parentNode.removeChild(mainNode);}
else{mainNode=elem.parentNode.parentNode.parentNode;mainNode.parentNode.removeChild(mainNode);}}
function contact_respond_req(elem,reqid,userid,contactid,contactname){Ext.MessageBox.show({title:'New Contact Request',msg:'You received a contact request from '+contactname+'.  Do you want to confirm and add them to your contact list?',width:300,buttons:Ext.MessageBox.YESNOCANCEL,fn:function(btn,text){if(btn=='yes'){Ext.Ajax.request({url:M.cfg.wwwroot+'/local/utilities/contacts/action.php',method:'GET',success:function(response,options){if(response['responseText'].indexOf('success')>=0){removeContactNotification(elem);Ext.Msg.alert('Success','You have successfully confirmed the contact request from '+contactname+'.');window.location.reload();}
else{Ext.Msg.alert('Error','Your confirmation to the contact request from '+contactname+' was unsuccessful.');}},failure:function(){Ext.Msg.alert('Error','There was an error while confirming the request from '+contactname+'.  Please try again. If problems persist, please contact us.')},params:{reqid:reqid,userid:userid,contactid:contactid,action:'confirm'}});}}});};function ignore_contact_req(elem,reqid,userid,contactid,contactname){Ext.MessageBox.show({title:'New Contact Request',msg:'You received a contact request from '+contactname+'.  Do you want to ignore and remove this request?',width:300,buttons:Ext.MessageBox.YESNOCANCEL,fn:function(btn,text){if(btn=='yes'){Ext.Ajax.request({url:M.cfg.wwwroot+'/local/utilities/contacts/action.php',method:'GET',success:function(response,options){if(response['responseText'].indexOf('success')>=0){removeContactNotification(elem);Ext.Msg.alert('Success','You have successfully denied the contact request from '+contactname+'.');}
else{Ext.Msg.alert('Error','Your denial to the contact request from '+contactname+' was unsuccessful.');}},failure:function(){Ext.Msg.alert('Error','There was an error while denying the request from '+contactname+'.  Please try again. If problems persist, please contact us.')},params:{reqid:reqid,userid:userid,contactid:contactid,action:'ignore'}});}}});};function contact_remove(userid,contactid,contactname,pagenum,current_userid){Ext.MessageBox.show({title:'Delete Contact',msg:'Are you sure you want to remove '+contactname+' from your contact list?',width:300,buttons:Ext.MessageBox.YESNO,fn:function(btn,text){if(btn=='yes'){Ext.Ajax.request({url:M.cfg.wwwroot+'/local/utilities/contacts/action.php',method:'GET',success:function(response,options){reload_contact(pagenum,current_userid);},failure:function(){Ext.Msg.alert('Error','There was an error while removing '+contactname+' from your contact list.  Please try again. If problems persist, please contact us.')},params:{userid:userid,contactid:contactid,action:'remove'}});}}});}
function reload_contact(pagenum,current_userid){if(pagenum!=0){var url=window.location.pathname;var filename=url.substring(url.lastIndexOf('/')+1);window.location=M.cfg.wwwroot+'/my/'+filename+'?id='+current_userid+'&page='+pagenum;}else{window.location.reload();}};function group_join(userid,groupid,groupname){Ext.MessageBox.show({title:'Join Group',msg:'Are you sure you want to join the group \"'+unescape(groupname)+'\"?',width:300,buttons:Ext.MessageBox.YESNO,fn:function(btn,text){if(btn=='yes'){Ext.Ajax.request({url:M.cfg.wwwroot+'/local/groups/action.php',method:'GET',success:function(response,options){Ext.Msg.alert('Success','You have successfully joined the group \"'+unescape(groupname)+'\".');updateGroupBtmInfo(groupid);},failure:function(){Ext.Msg.alert('Error','There was an error while joining the group \"'+unescape(groupname)+'\".  Please try again. If problems persist, please contact us.')},params:{userid:userid,groupid:groupid,action:'join'}});}}});}
function group_join_invite(grouptype,userid,groupid,groupname){Ext.MessageBox.show({title:'Join Group',msg:"Are you sure you want to join the group "+unescape(groupname)+"?",width:300,buttons:Ext.MessageBox.YESNO,fn:function(btn,text){if(btn=='yes'){Ext.Ajax.request({url:M.cfg.wwwroot+'/local/groups/action.php',method:'GET',success:function(response,options){Ext.Msg.alert('Success',"You have successfully joined the group "+unescape(groupname));url=M.cfg.wwwroot+"/local/groups/group.php?groupid="+groupid+"&type="+grouptype+"&page=wall";window.location=url;},failure:function(){Ext.Msg.alert('Error','There was an error while joining the group \"'+unescape(groupname)+'\".  Please try again. If problems persist, please contact us.')},params:{userid:userid,groupid:groupid,action:'invite_join'}});}}});}
function group_join_invite_ignore(parentid,countid,userid,groupid,groupname,requestedby){Ext.MessageBox.show({title:'Ignore Invite',msg:'Are you sure you want to decline the join request of the group \"'+unescape(groupname)+'\"?',width:300,buttons:Ext.MessageBox.YESNO,fn:function(btn,text){if(btn=='yes'){Ext.Ajax.request({url:M.cfg.wwwroot+'/local/groups/action.php',method:'GET',success:function(response,options){Ext.Msg.alert('Success','You have declined the request to join the group \"'+unescape(groupname)+'\".');removeMyInvite(parentid,countid);},failure:function(){Ext.Msg.alert('Error','There was an error while declining the Join request for the group \"'+unescape(groupname)+'\".  Please try again. If problems persist, please contact us.')},params:{userid:userid,groupid:groupid,requestedby:requestedby,action:'invite_ignore'}});}}});}
function removeMyInvite(pID,cID)
{var parentObj=document.getElementById(pID);if(parentObj){var itemToDelete=document.getElementById(cID);parentObj.removeChild(itemToDelete);if(cID=='invitet_0')
{document.getElementById('groupInviteContainer').style.display='none';}}}
function group_remove(id,userid,groupid,groupname,redirect){if(typeof(redirect)=="undefined"){redirect='false';}
Ext.MessageBox.show({title:'Leave Group',msg:"Are you sure you want to remove yourself from the group "+unescape(groupname)+"?",width:300,buttons:Ext.MessageBox.YESNO,fn:function(btn,text){if(btn=='yes'){Ext.Ajax.request({url:M.cfg.wwwroot+'/local/groups/action.php',method:'GET',success:function(response,options){Ext.Msg.alert('Success',"You have successfully left the group "+unescape(groupname));if(redirect=='true'){window.location=M.cfg.wwwroot+'/local/groups/searchgroups.php';}else{removeMyGroup(id);}},failure:function(){Ext.Msg.alert('Error','There was an error while removing \"'+unescape(groupname)+'\" from your group list. Please try again. If problems persist, please contact us.')},params:{userid:userid,groupid:groupid,action:'remove'}});}}});}
function group_delete(userid,groupid,groupname){Ext.MessageBox.show({title:'Delete Group',msg:'Are you absolutely sure you want to delete \"'+groupname+'\" and all the data it contains?   This action is final, and can not be undone!  ',width:300,buttons:Ext.MessageBox.YESNO,fn:function(btn,text){if(btn=='yes'){Ext.Ajax.request({url:M.cfg.wwwroot+'/local/groups/action.php',method:'GET',success:function(response,options){Ext.Msg.alert('Success','You have successfully delete the group \"'+groupname+'\".');},failure:function(){Ext.Msg.alert('Error','There was an error while deleting \"'+groupname+'\". Please try again. If problems persist, please contact us.')},params:{userid:userid,groupid:groupid,action:'delete'}});}}});};function getRequester(){var req=null;try{req=new XMLHttpRequest();}catch(error){try{req=new ActiveXObject("Microsoft.XMLHTTP");}catch(error){return false;}}
return req;}