Ext.ns('Ext.ux.form');Ext.ux.form.DateTime=Ext.extend(Ext.form.Field,{dateValidator:null,defaultAutoCreate:{tag:'input',type:'hidden'},dtSeparator:' ',hiddenFormat:'Y-m-d H:i:s',otherToNow:true,timePosition:'right',timeValidator:null,timeWidth:100,dateFormat:'m/d/y',timeFormat:'g:i A',initComponent:function(){Ext.ux.form.DateTime.superclass.initComponent.call(this);var dateConfig=Ext.apply({},{id:this.id+'-date',format:this.dateFormat||Ext.form.DateField.prototype.format,width:this.timeWidth,selectOnFocus:this.selectOnFocus,validator:this.dateValidator,listeners:{blur:{scope:this,fn:this.onBlur},focus:{scope:this,fn:this.onFocus}}},this.dateConfig);this.df=new Ext.form.DateField(dateConfig);this.df.ownerCt=this;delete(this.dateFormat);var timeConfig=Ext.apply({},{id:this.id+'-time',format:this.timeFormat||Ext.form.TimeField.prototype.format,width:this.timeWidth,selectOnFocus:this.selectOnFocus,validator:this.timeValidator,listeners:{blur:{scope:this,fn:this.onBlur},focus:{scope:this,fn:this.onFocus}}},this.timeConfig);this.tf=new Ext.form.TimeField(timeConfig);this.tf.ownerCt=this;delete(this.timeFormat);this.relayEvents(this.df,['focus','specialkey','invalid','valid']);this.relayEvents(this.tf,['focus','specialkey','invalid','valid']);this.on('specialkey',this.onSpecialKey,this);},onRender:function(ct,position){if(this.isRendered){return;}
Ext.ux.form.DateTime.superclass.onRender.call(this,ct,position);var t;if('below'===this.timePosition||'bellow'===this.timePosition){t=Ext.DomHelper.append(ct,{tag:'table',style:'border-collapse:collapse',children:[{tag:'tr',children:[{tag:'td',style:'padding-bottom:1px',cls:'ux-datetime-date'}]},{tag:'tr',children:[{tag:'td',cls:'ux-datetime-time'}]}]},true);}
else{t=Ext.DomHelper.append(ct,{tag:'table',style:'border-collapse:collapse',children:[{tag:'tr',children:[{tag:'td',style:'padding-right:4px',cls:'ux-datetime-date'},{tag:'td',cls:'ux-datetime-time'}]}]},true);}
this.tableEl=t;this.wrap=t.wrap({cls:'x-form-field-wrap'});this.wrap.on("mousedown",this.onMouseDown,this,{delay:10});this.df.render(t.child('td.ux-datetime-date'));this.tf.render(t.child('td.ux-datetime-time'));this.df.el.swallowEvent(['keydown','keypress']);this.tf.el.swallowEvent(['keydown','keypress']);if('side'===this.msgTarget){var elp=this.el.findParent('.x-form-element',10,true);if(elp){this.errorIcon=elp.createChild({cls:'x-form-invalid-icon'});}
var o={errorIcon:this.errorIcon,msgTarget:'side',alignErrorIcon:this.alignErrorIcon.createDelegate(this)};Ext.apply(this.df,o);Ext.apply(this.tf,o);}
this.el.dom.name=this.hiddenName||this.name||this.id;this.df.el.dom.removeAttribute("name");this.tf.el.dom.removeAttribute("name");this.isRendered=true;this.updateHidden();},adjustSize:Ext.BoxComponent.prototype.adjustSize,alignErrorIcon:function(){this.errorIcon.alignTo(this.tableEl,'tl-tr',[2,0]);},initDateValue:function(){this.dateValue=this.otherToNow?new Date():new Date(1970,0,1,0,0,0);},clearInvalid:function(){this.df.clearInvalid();this.tf.clearInvalid();},markInvalid:function(msg){this.df.markInvalid(msg);this.tf.markInvalid(msg);},beforeDestroy:function(){if(this.isRendered){this.wrap.removeAllListeners();this.wrap.remove();this.tableEl.remove();this.df.destroy();this.tf.destroy();}},disable:function(){if(this.isRendered){this.df.disabled=this.disabled;this.df.onDisable();this.tf.onDisable();}
this.disabled=true;this.df.disabled=true;this.tf.disabled=true;this.fireEvent("disable",this);return this;},enable:function(){if(this.rendered){this.df.onEnable();this.tf.onEnable();}
this.disabled=false;this.df.disabled=false;this.tf.disabled=false;this.fireEvent("enable",this);return this;},focus:function(){this.df.focus();},getPositionEl:function(){return this.wrap;},getResizeEl:function(){return this.wrap;},getValue:function(){return this.dateValue?new Date(this.dateValue):'';},isValid:function(){return this.df.isValid()&&this.tf.isValid();},isVisible:function(){return this.df.rendered&&this.df.getActionEl().isVisible();},onBlur:function(f){if(this.wrapClick){f.focus();this.wrapClick=false;}
if(f===this.df){this.updateDate();}
else{this.updateTime();}
this.updateHidden();this.validate();(function(){if(!this.df.hasFocus&&!this.tf.hasFocus){var v=this.getValue();if(String(v)!==String(this.startValue)){this.fireEvent("change",this,v,this.startValue);}
this.hasFocus=false;this.fireEvent('blur',this);}}).defer(100,this);},onFocus:function(){if(!this.hasFocus){this.hasFocus=true;this.startValue=this.getValue();this.fireEvent("focus",this);}},onMouseDown:function(e){if(!this.disabled){this.wrapClick='td'===e.target.nodeName.toLowerCase();}},onSpecialKey:function(t,e){var key=e.getKey();if(key===e.TAB){if(t===this.df&&!e.shiftKey){e.stopEvent();this.tf.focus();}
if(t===this.tf&&e.shiftKey){e.stopEvent();this.df.focus();}
this.updateValue();}
if(key===e.ENTER){this.updateValue();}},reset:function(){this.df.setValue(this.originalValue);this.tf.setValue(this.originalValue);},setDate:function(date){this.df.setValue(date);},setTime:function(date){this.tf.setValue(date);},setSize:function(w,h){if(!w){return;}
if('below'===this.timePosition){this.df.setSize(w,h);this.tf.setSize(w,h);if(Ext.isIE){this.df.el.up('td').setWidth(w);this.tf.el.up('td').setWidth(w);}}
else{this.df.setSize(w-this.timeWidth-4,h);this.tf.setSize(this.timeWidth,h);if(Ext.isIE){this.df.el.up('td').setWidth(w-this.timeWidth-4);this.tf.el.up('td').setWidth(this.timeWidth);}}},setValue:function(val){if(!val&&true===this.emptyToNow){this.setValue(new Date());return;}
else if(!val){this.setDate('');this.setTime('');this.updateValue();return;}
if('number'===typeof val){val=new Date(val);}
else if('string'===typeof val&&this.hiddenFormat){val=Date.parseDate(val,this.hiddenFormat);}
val=val?val:new Date(1970,0,1,0,0,0);var da;if(val instanceof Date){this.setDate(val);this.setTime(val);this.dateValue=new Date(Ext.isIE?val.getTime():val);}
else{da=val.split(this.dtSeparator);this.setDate(da[0]);if(da[1]){if(da[2]){da[1]+=da[2];}
this.setTime(da[1]);}}
this.updateValue();},setVisible:function(visible){if(visible){this.df.show();this.tf.show();}else{this.df.hide();this.tf.hide();}
return this;},show:function(){return this.setVisible(true);},hide:function(){return this.setVisible(false);},updateDate:function(){var d=this.df.getValue();if(d){if(!(this.dateValue instanceof Date)){this.initDateValue();if(!this.tf.getValue()){this.setTime(this.dateValue);}}
this.dateValue.setMonth(0);this.dateValue.setFullYear(d.getFullYear());this.dateValue.setMonth(d.getMonth(),d.getDate());}
else{this.dateValue='';this.setTime('');}},updateTime:function(){var t=this.tf.getValue();if(t&&!(t instanceof Date)){t=Date.parseDate(t,this.tf.format);}
if(t&&!this.df.getValue()){this.initDateValue();this.setDate(this.dateValue);}
if(this.dateValue instanceof Date){if(t){this.dateValue.setHours(t.getHours());this.dateValue.setMinutes(t.getMinutes());this.dateValue.setSeconds(t.getSeconds());}
else{this.dateValue.setHours(0);this.dateValue.setMinutes(0);this.dateValue.setSeconds(0);}}},updateHidden:function(){if(this.isRendered){var value=this.dateValue instanceof Date?this.dateValue.format(this.hiddenFormat):'';this.el.dom.value=value;}},updateValue:function(){this.updateDate();this.updateTime();this.updateHidden();return;},validate:function(){return this.df.validate()&&this.tf.validate();},renderer:function(field){var format=field.editor.dateFormat||Ext.ux.form.DateTime.prototype.dateFormat;format+=' '+(field.editor.timeFormat||Ext.ux.form.DateTime.prototype.timeFormat);var renderer=function(val){var retval=Ext.util.Format.date(val,format);return retval;};return renderer;}});Ext.reg('xdatetime',Ext.ux.form.DateTime);;Ext.namespace('Ext.bb');if(!course_id){course_id=1;}
var winnotif;winleft=60;if(audienceoptions.audience_thissection){if(audienceoptions.audience_mysections&&audienceoptions.audience_allcoursesections){winheight=250;}else{winheight=200;}}else if(audienceoptions.audience_allusers)
{winheight=250;}
else{winheight=150;}
wintop=40;title=postannouncement_title;_loadAnnouncementWindows=function(){Ext.bb.AnnouncementsWindowButtons=function(config){this.name="Ext.bb.AnnouncementsWindowButtons",Ext.apply(this,config||{});this.addEvents("beforeok","aftersubmit","beforecancel","beforeclose");Ext.bb.AnnouncementsWindowButtons.superclass.constructor.call(this);}
if(typeof stnotes_global!='undefined')
{loadStickyNotes(stnotes_global);if(Ext.get("announce_pager")){showPager(stnotes_global);}}
var starttime={xtype:'xdatetime',id:'starttime',hidden:true,cls:'x-btn-icon',fieldLabel:'Start Time',width:100,anchor:'-18',timeFormat:'H:i:s',timeConfig:{altFormats:'H:i:s',allowBlank:false},dateFormat:'n/d/Y',dateConfig:{altFormats:'Y-m-d|Y-n-d',allowBlank:false}};var endtime={xtype:'xdatetime',id:'endtime',cls:'x-btn-icon',fieldLabel:'End Time',width:100,anchor:'-18',timeFormat:'h:i A',timeConfig:{altFormats:'H:i:s',allowBlank:false},dateFormat:'n/d/Y',dateConfig:{altFormats:'Y-m-d|Y-n-d',allowBlank:false,editable:false}};var apublisher=new Ext.FormPanel({id:'announcement_publisher_panel',height:250,width:450,layout:'form',reader:new Ext.data.XmlReader({record:'announcement',success:'@success'},['starttime','endtime']),items:[new Ext.form.FieldSet({title:'',height:750,defaultType:'textfield',layout:'form',style:'border: none;',items:[starttime,endtime,new Ext.form.FieldSet({title:'',width:680,height:100,id:'audience_fieldset',hidden:!(audienceoptions.audience_thissection||audienceoptions.audience_allusers),hideLabel:!(audienceoptions.audience_thissection||audienceoptions.audience_allusers),defaultType:'radio',style:'border: none; margin-left: -10px;margin-top: 0px;margin-bottom: 0px;',items:[{xtype:'radio',fieldLabel:'Audience',id:'audience_thissection',hidden:!audienceoptions.audience_thissection,name:'audience',inputValue:1,checked:audienceoptions.audience_thissection,boxLabel:'<span class="session_radio_box_label">This Section Only</span>'},{xtype:'radio',id:'audience_mysections',hidden:!audienceoptions.audience_mysections,name:'audience',inputValue:2,checked:false,ctCls:'textmarginleft',boxLabel:'<span class="session_radio_box_label">All sections I teach</span>'},{xtype:'radio',id:'audience_allcoursesections',hidden:!audienceoptions.audience_allcoursesections,name:'audience',inputValue:3,checked:false,ctCls:'textmarginleft',boxLabel:'<span class="session_radio_box_label">All sections of the course</span>'},{xtype:'radio',id:'audience_allusers',hidden:!audienceoptions.audience_allusers,name:'audience',inputValue:5,checked:audienceoptions.audience_allusers,ctCls:'textmarginleft',boxLabel:'<span class="session_radio_box_label">All Users</span>'},{xtype:'radio',id:'audience_faculty',hidden:!audienceoptions.audience_faculty,name:'audience',inputValue:6,checked:false,ctCls:'textmarginleft',boxLabel:'<span class="session_radio_box_label">All Faculty Members</span>'},{xtype:'radio',id:'audience_students',hidden:!audienceoptions.audience_students,name:'audience',inputValue:7,checked:false,ctCls:'textmarginleft',boxLabel:'<span class="session_radio_box_label">All Students</span>'}]})]})]});Ext.extend(Ext.bb.AnnouncementsWindowButtons,Ext.util.Observable,{init:function(winnotif){this.winnotif=winnotif;if(this.closeBtn){winnotif.addButton({text:'Close'},this.onClose,this);}
else{winnotif.addButton({id:'submit_id',text:'Save'},this.onOkHit,this);winnotif.addButton({text:'Cancel',width:55},this.onCancelHit,this);}},onOkHit:function(btn,ev){this.winnotif.focus();var startdate=Ext.getCmp('starttime').getValue();var parse_startdate=Date.parse(startdate);var enddate=Ext.getCmp('endtime').getValue();var parse_enddate=Date.parse(enddate);if(parse_enddate>=parse_startdate)
{if(parse_enddate==parse_startdate)
{Ext.Msg.alert('Invalid','Enter Valid End Time');return false;}}
else
{Ext.Msg.alert('Invalid','Enter Valid End Date');return false;}
var post_announcement_btn=Ext.getCmp('sharetype');if(post_announcement_btn instanceof Ext.form.ComboBox){var post_msg_btn=Ext.getCmp('wall_publisher_btn');post_msg_btn.setText('<b>Post Announcement</b>');this.winnotif[this.winnotif.closeAction]();}else{submitAnnouncement(0);}
form1=apublisher.getForm();form1.submit({url:M.cfg.wwwroot+'/local/announcements/action.php',success:function(f,a){if(Ext.get('announce_pager')){reloadAnnouncements(stnotes_global.start,stnotes_global.page,stnotes_global.user_id);}else{reloadStickyNotes();}
var publisher=Ext.getCmp('wall_publisher_panel');var post_url=Ext.getCmp('wall-attachment-url');var post_photo=Ext.getCmp('wall-attachment-photo');var post_video=Ext.getCmp('wall-attachment-video');var post_file=Ext.getCmp('wall-attachment-file');var post_msg_btn=Ext.getCmp('wall_publisher_btn');attachment_panel.layout.setActiveItem(0);attachment_panel.collapse(true);publisher.fireEvent('resize',{});post_msg.reset();post_url.reset();post_photo.reset();post_video.reset();post_file.reset();post_msg_btn.setDisabled(false);apublisher.getForm().reset();Ext.getCmp('submit_id').enable();this.winnotif[this.winnotif.closeAction]();},failure:function(response,a){if(a.result.message){msg=a.result.message;}else{msg='';}
Ext.Msg.alert('Warning','Could not save. '+msg);if(a.result.failuretype&&(a.result.failuretype=='login'||a.result.failuretype=='permission')){window.parent.document.location.reload();return;}
Ext.getCmp('submit_id').enable();},params:{type:att_type,wall_msg:message,wall_attachment:attachment,wall_type:wall_type,wall_context_id:wall_context_id,course_id:course_id}});Ext.getCmp('submit_id').disable();return true;},onCancelHit:function(btn,ev){if(this.fireEvent("beforecancel",this,this.winnotif)!==false){apublisher.getForm().reset();Ext.getCmp('submit_id').enable();this.winnotif[this.winnotif.closeAction]();}}});if(Ext.get("add_edit_notif")){winnotif=new Ext.Window({applyTo:'add_edit_notif',closable:true,layout:'fit',autoWidth:true,height:winheight,closeAction:'hide',x:winleft,y:wintop,plain:true,modal:false,title:'<span style="text-transform: capitalize">'+title+'</span>',plugins:new Ext.bb.AnnouncementsWindowButtons({url:M.cfg.wwwroot+'/local/announcements/action.php',listener:{scope:this,'beforeok':function onBeforeOk(plugin,form,action){}}}),items:[apublisher]});}};if(navigator.userAgent.match(/Trident\/7/i)){setTimeout(_loadAnnouncementWindows(),5000);}else if(navigator.userAgent.match(/Edge/i)){setTimeout(_loadAnnouncementWindows(),5000);}else if(navigator.userAgent.match(/Trident\/6/i)){Ext.onReady(_loadAnnouncementWindows());}
else{window.addEventListener('load',function(){_loadAnnouncementWindows();},false);}
function submitAnnouncement(delaysubmit){var post_msg=Ext.getCmp('wall_publisher_textarea');var message=post_msg.getValue();var attachment_panel=Ext.getCmp('wall_attachment_panel');var att_type=attachment_panel.layout.activeItem.id;var attachment='';if(attachment_panel.layout.activeItem.id!='wall-attachment-none'){attachment=attachment_panel.layout.activeItem.getValue();valid=attachment_panel.layout.activeItem.validate();}
var apublisher=Ext.getCmp('announcement_publisher_panel');form1=apublisher.getForm();form1.submit({url:M.cfg.wwwroot+'/local/announcements/action.php',success:function(f,a){if(Ext.get('announce_pager')){reloadAnnouncements(stnotes_global.start,stnotes_global.page,stnotes_global.user_id);}else{reloadStickyNotes();}
reset_post_items();apublisher.getForm().reset();if(delaysubmit==0){Ext.getCmp('submit_id').enable();this.winnotif[this.winnotif.closeAction]();}},failure:function(f,a){Ext.Msg.alert('Warning','Could not save');Ext.getCmp('submit_id').enable();},params:{type:att_type,wall_msg:message,wall_attachment:attachment,wall_type:wall_type,wall_context_id:wall_context_id,course_id:course_id}});if(delaysubmit==0){Ext.getCmp('submit_id').disable();}}
function createStickyNotesPost(data)
{if(data=='undefined'||data==undefined){return false;}
var wallmessage='';var wallhtml='';wallhtml+='<div class="content-wrapper">';if(data.canDelete)
{wallhtml+='<div class="action-links">';wallhtml+='<a href="javascript:void(0);" class="update" title="Update This Post" onClick="javascript:editAnnouncementWindow('+data.id+');"></a>';wallhtml+='<a href="javascript:void(0);" class="remove" title="Delete This Post" onClick="javascript:delete_announcement('+data.id+');"></a>';wallhtml+='</div>';}
wallhtml+='<div class="thumbnail-wrapper">';wallhtml+='<img title="Announcement" alt="Announcement" src="'+M.util.image_url('wall-post-alert','theme')+'" >';wallhtml+='</div>';wallhtml+='<div class="details">';wallhtml+='<div class="name">'+data.posterData+'</div>';wallhtml+='<div class="date">'+data.dateFormatted+'</div>';if((data.post_content_type!='wall-attachment-photo')&&(data.post_content_type!='wall-attachment-video')){wallhtml+='<div class="post">'+data.post_text+'</div>';}else{wallhtml+='<div class="post"></div>';}
wallhtml+='</div>';wallhtml+='<div class="bottom-info">';wallhtml+='<div class="attachment">';if(data.post_content_type=='wall-attachment-url')
{wallhtml+='<a href="'+data.url+'" target="_blank">'+data.url+'</a>';}
else if(data.post_content_type=='wall-attachment-photo')
{wallhtml+='<div class="mvm uiStreamAttachments clearfix">';wallhtml+='<div class="UIImageBlock clearfix">';wallhtml+='<a class="uiPhotoThumb UIImageBlock_Image UIImageBlock_MED_Image" href="javascript:void(0);" title="" rel="photo"><img onclick = "toggle_wall_pic_size(\'sn_img_'+data.id+'\')" class="img" src="'+data.picture_data+'" alt="" id ="sn_img_'+data.id+'"></a>';wallhtml+='<div class="UIImageBlock_Content UIImageBlock_MED_Content fsm fwn fcg">';wallhtml+='<div class="uiAttachmentTitle"><strong><span>'+data.post_text+'</span></strong></div>';wallhtml+='</div>';wallhtml+='</div>';wallhtml+='</div>';}
else if(data.post_content_type=='wall-attachment-video')
{wallhtml+='<div class="mvm uiStreamAttachments clearfix">';wallhtml+='<div class="UIImageBlock clearfix"><span class="uiVideoThumb UIImageBlock_Image UIImageBlock_MED_Image" >'+data.video_icon+'<i></i></span>';wallhtml+='<div class="UIImageBlock_Content UIImageBlock_MED_Content fsm fwn fcg">';wallhtml+='<div class="uiAttachmentTitle"><strong><span>'+data.post_text+'</span></strong> </div>';wallhtml+='<div class="mts uiAttachmentDesc">';wallhtml+='<div>';wallhtml+='<!--<div class="fsm fwn fcg">Length: <span class="uiAttachmentDetails">‎1:27</span></div>//-->';wallhtml+='</div>';wallhtml+='</div>';wallhtml+='</div>';wallhtml+='</div>';wallhtml+='</div>';}
else if(data.post_content_type=='wall-attachment-file')
{wallhtml+='<a href="'+M.cfg.wwwroot+'/local/files/lib/download.php?id='+data.file_data+'&userid='+data.userid+'" target="_blank">'+data.displayname+'</a>';}
wallhtml+='</div>';wallhtml+='</div>';wallhtml+='</div>';return wallhtml;}
function addStickyNotesPost(postData,item_id,class_name)
{var parentObj=document.getElementById('notif-wraper');var newRow=document.createElement('li');var rowID='stnote_'+item_id;newRow.setAttribute('id',rowID);class_name=class_name+' alert sticky';newRow.setAttribute('class',class_name);newRow.innerHTML=postData;parentObj.appendChild(newRow);}
function loadStickyNotes(stnotes_global,reset){if(reset==1){var ul=document.getElementById('notif-wraper');if(ul){while(ul.firstChild){ul.removeChild(ul.firstChild);}}}
if(stnotes_global.postCount>0){var post_ct=0;for(var i=0;i<stnotes_global.wallPosts.length;i++)
{var wallPost=createStickyNotesPost(stnotes_global.wallPosts[i]);addStickyNotesPost(wallPost,stnotes_global.wallPosts[i].id,'wall-item');post_ct++;}}}
function showPager(stnotes_global)
{var parentObj=document.getElementById('announce_pager');var pagerHtml='';if(stnotes_global.postCount>0){var startVal=(parseInt(stnotes_global.page)==1)?parseInt(stnotes_global.page):(parseInt(stnotes_global.page)-1)*parseInt(stnotes_global.announcements_per_page)+1;var toVal=((parseInt(stnotes_global.start)+parseInt(stnotes_global.announcements_per_page))<parseInt(stnotes_global.totalAnnounceCount))?parseInt(stnotes_global.start)+parseInt(stnotes_global.announcements_per_page):stnotes_global.totalAnnounceCount;if(stnotes_global.numPages>1)
{pagerHtml+='<div class="summary lfloat fsm fcg">'+startVal+'-'+toVal+' of '+stnotes_global.totalAnnounceCount+' Announcements</div>';pagerHtml+='<div class="rfloat">';if(parseInt(stnotes_global.prevPage)>0)
pagerHtml+='<a class="prev uiButton uiButtonNoText" role="button" href="#" onClick="javascript:reloadAnnouncements('+stnotes_global.prevStart+','+stnotes_global.prevPage+','+stnotes_global.user_id+');"><i class="mrs customimg img sp_7cgixs sx_427f28"></i><span class="uiButtonText"></span></a>';else
pagerHtml+='<a class="prev uiButtonDisabled uiButton uiButtonNoText" role="button" href="#"><i class="mrs customimg img sp_7cgixs sx_427f28"></i><span class="uiButtonText"></span></a>';if(parseInt(stnotes_global.nextPage)<=parseInt(stnotes_global.numPages))
pagerHtml+='<a class="next uiButton uiButtonNoText" role="button" href="#" onClick="javascript:reloadAnnouncements('+stnotes_global.nextStart+','+stnotes_global.nextPage+','+stnotes_global.user_id+');"><i class="mrs customimg img sp_7cgixs sx_c2e31c"></i><span class="uiButtonText"></span></a>';else
pagerHtml+='<a class="next uiButtonDisabled uiButton uiButtonNoText" role="button" href="#"><i class="mrs customimg img sp_7cgixs sx_c2e31c"></i><span class="uiButtonText"></span></a>';pagerHtml+='</div>';}
else
{pagerHtml+='<div class="summary lfloat fsm fcg">1-'+stnotes_global.totalAnnounceCount+' of '+stnotes_global.totalAnnounceCount+' Announcements</div>';}}
parentObj.innerHTML=pagerHtml;}
function reloadAnnouncements(start,page,user_id)
{load_wall_type=wall_type_announce;Ext.Ajax.request({url:M.cfg.wwwroot+'/local/announcements/all_announcements.php',method:'GET',waitMsg:'Loading Announcements...',success:function(response,options){stnotes_global=Ext.decode(response.responseText);var parentObj=document.getElementById('notif-wraper');var pagerContainer=document.getElementById('announce_pager');parentObj.innerHTML='';var post_ct=0;loadStickyNotes(stnotes_global,1);showPager(stnotes_global);},failure:function(){},params:{start:start,page:page,id:user_id,ajaxcall:1,wall_type:wall_type,wall_context_id:wall_context_id}});}
function delete_announcement(del_announce_id)
{Ext.MessageBox.show({title:'Delete Announcement',msg:'Are you sure you want to delete this announcement',width:300,buttons:Ext.MessageBox.YESNO,fn:function(btn,text){if(btn=='yes'){Ext.Ajax.request({url:M.cfg.wwwroot+'/local/announcements/delete_announcement.php',method:'POST',success:function(response,options){if(Ext.get('announce_pager')){if(stnotes_global.postCount>0){reloadAnnouncements(stnotes_global.start,stnotes_global.page,stnotes_global.user_id);}else{reloadAnnouncements(0,1,0);}}else{reloadStickyNotes();}},failure:function(){Ext.Msg.alert('Error','There was an error while deleting wall post.  Please try again. If problems persist, please contact us.')},params:{action:'deleteannouncement',announce_id:del_announce_id,wall_type:wall_type,wall_context_id:wall_context_id}});}}});}
function reloadStickyNotes(){load_wall_type=wall_type_announce;Ext.Ajax.request({url:M.cfg.wwwroot+'/local/announcements/load_announcements.php',method:'POST',success:function(response){if(response['status']==200){stnotes_global=Ext.decode(response.responseText);loadStickyNotes(stnotes_global,1);}
else{Ext.Msg.alert('Error','Your post was unsuccessful.  Please try again. If problems persist, please contact us.');}},failure:function(response){Ext.Msg.alert('Error','An error occurred.  Please try again. If problems persist, please contact us.')},params:{wall_type:load_wall_type,wall_context_id:wall_context_id,announce_limit:announce_limit,course_id:course_id}});}
function editAnnouncementWindow(announceid){var editPublisher=Ext.getCmp('announcement_edit_publisher');editPublisher.getForm().load({url:M.cfg.wwwroot+'/local/announcements/loadsetting.php?announceid='+announceid});var editaudience=Ext.getCmp('editaudience_fieldset');editaudience.disable();var edittexteditor=Ext.getCmp('announcement_posttext');edittexteditor.show();editwindow.show();};var editwindow;wintop=40;winleft=60;edittitle=editannouncement_title;Ext.onReady(function(){var editstarttime={xtype:'xdatetime',id:'editstarttime',hidden:true,cls:'x-btn-icon',fieldLabel:'Start Time',width:100,anchor:'-18',timeFormat:'H:i:s',timeConfig:{altFormats:'H:i:s',allowBlank:false},dateFormat:'n/d/Y',dateConfig:{altFormats:'Y-m-d|Y-n-d',allowBlank:false}};var editendtime={xtype:'xdatetime',id:'editendtime',cls:'x-btn-icon',fieldLabel:'End Time',width:100,anchor:'-18',timeFormat:'h:i A',timeConfig:{altFormats:'H:i:s',allowBlank:false},dateFormat:'n/d/Y',dateConfig:{altFormats:'Y-m-d|Y-n-d',allowBlank:false,editable:false}};var audienceoption=new Ext.form.FieldSet({title:'',width:680,height:100,id:'editaudience_fieldset',hidden:!audienceoptions.audience_thissection,hideLabel:!audienceoptions.audience_thissection,defaultType:'radio',style:'border: none; margin-left: -10px;margin-top: 0px;margin-bottom: 0px;',items:[{xtype:'radio',fieldLabel:'Audience',id:'editaudience_thissection',name:'audience',inputValue:1,checked:true,boxLabel:'<span class="session_radio_box_label">This Section Only</span>'},{xtype:'radio',id:'editaudience_mysections',hidden:!audienceoptions.audience_mysections,name:'audience',inputValue:2,checked:false,ctCls:'textmarginleft',boxLabel:'<span class="session_radio_box_label">All sections I teach</span>'},{xtype:'radio',id:'editaudience_allcoursesections',hidden:!audienceoptions.audience_allcoursesections,name:'audience',inputValue:3,checked:false,ctCls:'textmarginleft',boxLabel:'<span class="session_radio_box_label">All sections of the course</span>'}]});Ext.QuickTips.init();Ext.form.Field.prototype.msgTarget="side";if(!audienceoptions.audience_thissection){editformheight=200;}else{editformheight=320;}
var edittexteditor=new Ext.form.HtmlEditor({fieldLabel:'Message',id:'announcement_posttext',name:'post_text',height:140,width:510,region:'center',allowBlank:true,enableLinks:false,enableSourceEdit:false});var editPublisher=new Ext.FormPanel({id:'announcement_edit_publisher',height:editformheight,width:550,layout:'form',frame:true,reader:new Ext.data.XmlReader({record:'announcement',success:'@success'},['editstarttime','editendtime','announcement_posttext','audience','announceid']),items:[editstarttime,editendtime,edittexteditor,audienceoption,{xtype:'hidden',id:'announceid',name:'edit_announce_id'}]});edittexteditor.hide();Ext.extend(Ext.bb.AnnouncementsWindowButtons,Ext.util.Observable,{init:function(editwindow){this.editwindow=editwindow;if(this.closeBtn){editwindow.addButton({text:'Close'},this.onClose,this);}
else{editwindow.addButton({id:'submit_announce',text:'Update'},this.onOkHit,this);editwindow.addButton({text:'Cancel',width:55},this.onCancelHit,this);}},onClose:function(btn,ev){edittexteditor.hide();},onOkHit:function(btn,ev){this.editwindow.focus();var startdate=Ext.getCmp('editstarttime').getValue();var parse_startdate=Date.parse(startdate);var enddate=Ext.getCmp('editendtime').getValue();var parse_enddate=Date.parse(enddate);if(parse_enddate>=parse_startdate)
{if(parse_enddate==parse_startdate)
{Ext.Msg.alert('Invalid','Enter Valid End Time');return false;}}
else
{Ext.Msg.alert('Invalid','Enter Valid End Date');return false;}
var post_msg=Ext.getCmp('announcement_posttext');var message=post_msg.getValue();editform=editPublisher.getForm();editform.submit({url:M.cfg.wwwroot+'/local/announcements/update.php',success:function(f,a){reloadStickyNotes();editPublisher.getForm().reset();Ext.getCmp('submit_announce').enable();this.editwindow[this.editwindow.closeAction]();},failure:function(f,a){Ext.Msg.alert('Warning','Could not save');Ext.getCmp('submit_announce').enable();},params:{wall_msg:message,wall_type:wall_type,wall_context_id:wall_context_id}});Ext.getCmp('submit_announce').disable();return true;},onCancelHit:function(btn,ev){if(this.fireEvent("beforecancel",this,this.editwindow)!==false){editPublisher.getForm().reset();Ext.getCmp('submit_announce').enable();this.editwindow[this.editwindow.closeAction]();}}});if(Ext.get("add_edit_announce")){editwindow=new Ext.Window({applyTo:'add_edit_announce',closable:true,layout:'fit',width:660,closeAction:'hide',x:winleft,y:wintop,modal:false,title:'<span style="text-transform: capitalize">'+edittitle+'</span>',plugins:new Ext.bb.AnnouncementsWindowButtons({url:M.cfg.wwwroot+'/local/announcements/update.php',listener:{scope:this,'beforeok':function onBeforeOk(plugin,form,action){}}}),items:[editPublisher]});}});