# Homework number: 7

# Run these three functions to get a clean test of homework code
# dev.off() # Clear the graph window
cat('\014')  # Clear the console
rm(list=ls()) # Clear user objects from the environment

library(BayesFactor)

# Question 3:
#   Run cor.test() on the correlation between "area" and "perm" in the rock data set
# and interpret the results. Note that you will have to use the "$" accessor to get
# at each of the two variables. Make sure you interpret both the confidence 
# interval and the p-value that is generated by cor.test().
data(rock)
View(rock)

# Capture just the area and perm values
rock.areas <- rock$area
rock.perms <- rock$perm

# Run a correlation t-test on the values. 
cor.test(rock.areas, rock.perms)

# Answer 3:
#   The null hypothesis is that there is no correlation between the area and perm. 
# The alternative hypothesis is that there is correlation between the area
# and perm.
# The p-value is pretty small and is below the threshold of 0.01 which is very good.
# From this we can reject the null hypothesis and state that the correlation between
# area and perm is not 0.
# The 95% Confidence Interval does not look to be very large which would speak 
# to a high level of confidence on the results. It also does not straddle 0 
# which is a support for the alternative hypothesis. The CI is all negative which 
# gives us a hint at how the correlation is possibly directed. We see a possible
# correlation of -0.396637. These are all hints and the only concrete result we can 
# take from this is that we are able to reject the null hypothesis


# Question 4:
#   Create a copy of the bfCorTest() custom function presented in this chapter.
# Don't forget to "source" it. Conduct a Bayesian analysis of the correlation 
# between "area" and "perm" in the rock data set.

# bfCorTest function found in the textbook and async material. 
bfCorTest <- function (x,y) # Get r from BayesFactor
{
  zx <- scale(x) # Standardize X
  zy <- scale(y) # Standardize Y
  zData <- data.frame(x=zx,rhoNot0=zy) # Put in a data frame
  bfOut <- generalTestBF(x ~ rhoNot0, data=zData) # linear coefficient
  mcmcOut <- posterior(bfOut,iterations=10000) # posterior samples
  print(summary(mcmcOut[,"rhoNot0"])) # Get the HDI for rho
  return(bfOut) # Return Bayes factor object
}

bfCorTest(rock.areas, rock.perms)

# Answer 4:
#   The Bayesian analysis supports the findings from the null hypothesis test and 
# CI. The mean of ~ -0.346 is pretty close to the correlation of -0.396637. The
# HDI is bigger than the CI predicted but the lower bound was really close to each
# other. The most important piece of information is the rhoNot0 which is at
# 8.072781 in favor of the alternative hypothesis with 0 margin of error. Anything 
# above a 3:1 is considered a positive evidence. Therefore, we can conclude that
# area and perm are not independent.

# Question 8:
#   Not unexpectedly, there is a data set in R that contains these data. The data set
# is called UCBAdmissions and you can access the department mentioned above like
# this: UCBAdmissions[,,1]. Make sure you put two commas before the 1: this is a 
# three dimensional contingency table that we are subsetting down to two dimensions.
# Run chisqp.test() on this subset of the data set and make sense of the results.

# Make 2 x 2 table function from the book.
make2x2table <- function(ul)
{
  ll <- 50 - ul
  ur <- 30 - ul
  lr <- 50 - ur
  matrix(c(ul,ur,ll,lr),nrow=2, ncol=2, byrow = T)
}

# Calc chi squared function from the book. 
calcChiSquared <- function(actual,expected)
{
  diffs <- actual - expected
  diffsSq <- diffs^2
  diffsSqNorm <- diffsSq/expected
  sum(diffsSqNorm)
}
# Play with the table maker. 
make2x2table(15)
calcChiSquared(make2x2table(15), make2x2table(15))

# Run a chi squared test 
chisq.test(UCBAdmissions[,,1], correct=F)

# Answer 8:
#   The Null Hypothesis is that gender and admit are independent of each other. The
# Alternative Hypothesis is that the correlation between gender and admit is not
# 0 and therefore they are not independent.
# The p-value is extremely low and will pass even the 0.001 threshold. Therefore,
# we can reject the null hypothesis and say that gender and admit are not 
# independent of each other

# Question 9:
#   Use the contingencyTableBF() to conduct a Bayes factor analysis on the UCB
# admissions data. Report and interpret the Bayes factor.

# Run a Bayesian analysis of the gender and admissions data.
ucbOut <- contingencyTableBF(UCBAdmissions[,,1],sampleType="poisson", posterior=F)
summary(ucbOut)

# Answer 9:
#   The Bayes factor of 1111.64 is in favor of the alternative hypothesis that gender
# and admit are not independent from each other. This factor is very high so there
# is a very strong evidence for the Alternative Hypothesis.


# Question 10:
#   Using the UCBA data, run contingencyTableBF() with posterior sampling. Use the 
# results to calculate a 95% HDI of the difference in proportions between the 
# columns.

# Run a Bayesian analysis of the gender and admissions data.
# Include posterior probability
ucbOut <- contingencyTableBF(UCBAdmissions[,,1], sampleType="poisson", 
                             posterior=T, iterations = 10000)
# Calculate admission status proportions for males
maleProp <- ucbOut[,"lambda[1,1]"]/ucbOut[,"lambda[2,1]"]
hist(maleProp)

# Calculate admission status proportions for females
femaleProp <- ucbOut[,"lambda[1,2]"]/ucbOut[,"lambda[2,2]"]
hist(femaleProp)

# Calculate the difference between males and females
propDiffs <- maleProp - femaleProp

# Plot the differences and include the 95% HDI lines.
hist(propDiffs, 
     main="Histogram of Proportion Differences - Male vs. Female", 
     col="darkslategray4", xlab="DIfference")
abline(v=quantile(propDiffs,c(0.025)), col="black")
abline(v=quantile(propDiffs,c(0.975)), col="black")


# Print the HDI interval
c(quantile(propDiffs,c(0.025)),quantile(propDiffs,c(0.975)))


# Answer 10:
#   We can see that none of the HDI ranges overlap with one another. Then a proportion
# distribution is created for each category of male and female. We can see that the 
# male proportions are most frequent a little above 1.6 and the female proportions
# are centered a little under 5. At this point, we take the difference between the
# two proportions and plot it. Plotting the lower bound of the HDI at about -6 and
# the upper bound at about -1.21, we can see that it does not straddle 0 and it is
# in the negative end. With this information we can see that the two categories
# are not independent and the most likely shift (as we go from male to female) is 
# -3.1 but can be as low as -5.98 and as high as -1.21.



